### ISSUE TITLE
Is it full data or partial one?

### ISSUE THREAD

**Issue by shantanuo** [abhijeet3922/Food-Classification-Task-Transfer-learning#1]
When I run this command...
len(train),len(val),len(test)

I get less number of results compared to your github repo.
(3001, 1001, 1001)
Your count:
(9866, 3430, 3347)

It means the data made available on dropbox is not complete. And therefore probably I get this error as well...

train_y = [int(img.split("/")[-1].split("_")[0]) for img in train]
ValueError: invalid literal for int() with base 10: '.DS'

Please let me know how to download the complete dataset and how to deal with above error.

**Comment by shantanuo** [comment]
" The data-set can be downloaded from here."
You have pointed to Food-5K data on dropbox while you have used Food-11 data in your script!
Once I downloaded the data from official site that you have mentioned, It worked as expected.
_____
The second error of Invalid Literal was because of a hidden file .DS_Store. Once I remove it from all folders, I can continue...
rm -rf evaluation/.DS_Store

Your blog is awesome by the way :)

**Comment by abhijeet3922** [comment]
Thanks for pointing. Did the wrong link. Will update.
